#!/bin/sh

#
# npm postinstall script
#
# Author: André König <andre.koenig@posteo.de> 
#

case $1 in
    install-pre-commit)
        if [ -d ".git" ]; then
            cp ./.scripts/pre-commit .git/hooks/pre-commit
        fi
    ;;
esac

exit $?