#!/bin/sh

#
# Git pre-commit hook for executing `gulp lint` before committing.
#
# Author: André König <andre.koenig@posteo.de> 
#

if git diff --cached --name-only --diff-filter=ACM | grep '.js$' >/dev/null 2>&1
    then
        ./node_modules/.bin/gulp lint
    fi

exit $?